### ISSUE TITLE
Deck_count_cut_no_change_2 

### ISSUE THREAD

**Issue by aosakwe** [Gadiguibou/comp-250-assignment-2-tester#11]
Hey! I was running this test and am not sure if it's correct. Based off of the instructions, if the value of the bottom card is a multiple of the total number of cards, no change should be made. However here the bottom card has a value of 12 and the deck has 13 cards. Shouldn't this method therefore undergo count-cut?

**Comment by Gadiguibou** [comment]
Glad you asked! That's one of the problems I encountered when writing the code. If you follow the instructions carefully you'll see nothing changes either when count-cutting the number of cards - 1. That's why I added a test for it. If you don't do it, you'll see your code crashes later on the tests for the generateNextKeystreamValue() method (from the example in the pdf).

Happy coding! :smile:

**Comment by aosakwe** [comment]
Thanks for the response! Yeah I looked into what my code was doing and it's true that there is no change for n-1 either. Will work on implementing that.
