### ISSUE TITLE
Deck_generate_next_keystream_value

### ISSUE THREAD

**Issue by rofe-dl** [Gadiguibou/comp-250-assignment-2-tester#17]
Hello, I may be wrong here but the test Deck_generate_next_keystream_value seems to give the wrong keystream value starting from the third. It is testing the code against the small example given at the end of the assignment. 

For the third value, I seem to get 14 but it's expected to get 15.
I did it by hand and detailed every step below to check for sure. I only included till the 4th method call as that's where the mismatch starts.

Am I making any mistakes in one of the steps below or is the test wrong?

Initially: 3C 3D AD 5C BJ 2C 2D 4D AC RJ 4C 5D - RJ will move down once

3C 3D AD 5C BJ 2C 2D 4D AC 4C RJ 5D  - BJ will move down twice
3C 3D AD 5C 2C 2D BJ 4D AC 4C RJ 5D  - triple-cut, cards left of BJ will swap with right of RJ
5D BJ 4D AC 4C RJ 3C 3D AD 5C 2C 2D  - count-cut, 2D has value 15 % 12 = 3, first 3 cards will move
AC 4C RJ 3C 3D AD 5C 2C 5D BJ 4D 2D  - AC has value 1, so moving down 1 time gives 4C = 4 is first value
Value obtained: 4

AC 4C RJ 3C 3D AD 5C 2C 5D BJ 4D 2D  - RJ will move down once
AC 4C 3C RJ 3D AD 5C 2C 5D BJ 4D 2D  - BJ will move down twice
AC 4C 3C RJ 3D AD 5C 2C 5D 4D 2D BJ  - triple-cut, cards left of RJ will swap with right of BJ
RJ 3D AD 5C 2C 5D 4D 2D BJ AC 4C 3C  - count-cut, 3C has value 3, first 3 cards will move
5C 2C 5D 4D 2D BJ AC 4C RJ 3D AD 3C  - 5C has value 5, so moving down 5 times gives us black joker
Joker hit, repeat algorithm

5C 2C 5D 4D 2D BJ AC 4C RJ 3D AD 3C  - RJ will move down once
5C 2C 5D 4D 2D BJ AC 4C 3D RJ AD 3C  - BJ will move down twice
5C 2C 5D 4D 2D AC 4C BJ 3D RJ AD 3C  - triple-cut, cards left of BJ will swap with right of RJ
AD 3C BJ 3D RJ 5C 2C 5D 4D 2D AC 4C  - count-cut, 4C has value 4, first 4 cards will move
RJ 5C 2C 5D 4D 2D AC AD 3C BJ 3D 4C  - RJ has value 11, so moving down 11 times gives us 4C = 4 as second value
Value obtained: 4

RJ 5C 2C 5D 4D 2D AC AD 3C BJ 3D 4C  - RJ will move down once
5C RJ 2C 5D 4D 2D AC AD 3C BJ 3D 4C  - BJ will move down twice
5C RJ 2C 5D 4D 2D AC AD 3C 3D 4C BJ  - triple-cut, cards left of RJ will swap with right of BJ
RJ 2C 5D 4D 2D AC AD 3C 3D 4C BJ 5C  - count-cut, 5C has value 5, first 5 cards will move
AC AD 3C 3D 4C BJ RJ 2C 5D 4D 2D 5C  - AC has value 1, so moving down 1 time gives us AD = 14
Value obtained: 14

**Comment by Gadiguibou** [comment]
Hi, I read through your steps and couldn't identify any mistakes. However, I used to have a similar (if not the same) result previously and managed to spot a bug in my code that caused the keystream to be incorrect.

Maybe you could post it on Piazza or contact a TA to see if someone else can spot something.

In the meantime, I'll let the test case as is since it's taken from the assignment instructions. If it turns out we all made the same mistake, I'll make sure to update it promptly.

Hope this helps!

Edit: I'm going to look at it one more time  by comparing the results after each pass to my implementation and see where yours differs. I'll let you know what I find.

**Comment by rofe-dl** [comment]
Alright, thank you!

**Comment by Gadiguibou** [comment]
Hi again, it seems you just might be right. Or at least, the behavior of the "correct" code is kind of weird.

Here's a diff:

![image](https://user-images.githubusercontent.com/34945306/110789892-604a5700-823e-11eb-823a-8be774799927.png)

On the right, is what's generated by my code and on the left is what's generated by yours.

Our decks differ at the step where the red joker needs to move down one position but is already at the top of the deck. My code currently changes the deck structure correctly but never updates the head for this operation. It's as if you were moving the cards below the top one to the bottom instead of moving the top one down *n* cards.

Since this still generates the *"right"* keystream, you may want to open an issue on Piazza about it. It may be that the teacher's code exhibits the same weird behavior.

@louis-hildebrand, could you take a look at this to see what your code does in that situation?

**Comment by rofe-dl** [comment]
Alright, thank you for that clarification.

**Comment by Gadiguibou** [comment]
This is, in fact, the desired behavior.

From Piazza [question 1299](https://piazza.com/class/kjktfrccki4217?cid=1299):

> moveCard() will always move the card inputted under another one found at p positions down from the inputted one, which is different from moving it p position down (where if you were in the last position, you would then become the first position) and explains why moveCard() does not update the head and also cannot move a card to the head.

Closing since the question was answered.
